version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-builder
    volumes:
      - ./frontend:/usr/src/frontend
    command: nodemon
    ports:
      - "3000:3000" # Adjust based on your app's port

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: rust-builder
    volumes:
      - ./backend:/usr/src/backend
    command: cargo watch -x run
    ports:
      - "8080:8080" # Adjust based on your app's port

